### PR TITLE
Issue #538 - Formatting and Linting

### PR DESCRIPTION
**Pull request by cjjacks**
Run `pre-commit run --all` to apply formatting to all files and updated the max line length to 120 characters

### CODE REVIEW

**Comment by nttoole** [comment]
```
(venv) bash-3.2$ pre-commit run --all-files
Trim Trailing Whitespace.................................................Passed
Fix End of Files.........................................................Passed
Check for merge conflicts................................................Passed
Debug Statements (Python)................................................Passed
Reorder python imports...................................................Passed
mypy.....................................................................Passed
black....................................................................Passed
flake8...................................................................Passed
AIT TLM YAML check.......................................................Passed
AIT CMD YAML check.......................................................Passed
AIT EVR YAML check.......................................................Passed
AIT LIMITS YAML check....................................................Passed
```


```
(venv) bash-3.2$ pytest
...
============================================= 250 passed, 2 skipped, 11 warnings in 4.47s ==============================================
```

Successfully configured and ran AIT-GUI and ait_example:

image

**Comment by nttoole** [comment]
@cjjacks Just checking if this is ready for final review or if there are any expected changes?  Thanks

**Comment by cjjacks** [comment]
@nttoole Sorry for the last minute update!  Was just double checking and realized that I had committed updates to the lock file which didn't necessarily belong in this PR.  Should be good to go now.

**Review by nttoole — APPROVED** [review]
Both code review and testing via GUI plugin pass.

**Pull request merged**
